# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_locations', '0004_auto_20160914_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embeddirectionsplugin',
            name='query',
        ),
        migrations.RemoveField(
            model_name='embedviewplugin',
            name='query',
        ),
    ]
